In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

# Leer los KPIs de la capa Gold
pd.options.display.float_format = '{:,.0f}'.format
kpi_dept = pd.read_parquet('../data/gold/kpi_educacion_por_departamento.parquet')
top_mun = pd.read_parquet('../data/gold/top_10_municipios_poblacion.parquet')

print("KPI POR DEPARTAMENTO")
display(kpi_dept.head(10))

print("\n TOP 10 MUNICIPIOS POR POBLACIÓN ")
display(top_mun)

KPI POR DEPARTAMENTO

,departamento,total_poblacion_5_16,promedio_tasa_matriculacion,promedio_cobertura_neta
0,AMAZONAS,"294,925",58,61
1,ANTIOQUIA,"15,756,527",87,88
2,ARAUCA,"917,468",80,83
3,"ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANT...","162,140",81,82
4,ARCHIPIÉLAGO DE SAN ANDRÉS. PROVIDENCIA Y SANT...,"11,169",85,85
5,ATLÁNTICO,"6,885,120",89,87
6,BOGOTÁ D.C.,"1,181,597",96,96
7,"BOGOTÁ, D.C.","16,023,954",87,89
8,BOLÍVAR,"6,214,541",87,87
9,BOYACÁ,"3,460,546",83,84

 TOP 10 MUNICIPIOS POR POBLACIÓN

,municipio,departamento,poblacion_5_16,tasa_matriculacion_5_16,cobertura_neta
0,"BOGOTÁ, D.C.","BOGOTÁ, D.C.","16,023,954",87,89
1,CALI,VALLE DEL CAUCA,"5,435,284",81,82
2,MEDELLÍN,ANTIOQUIA,"4,914,379",102,100
3,BARRANQUILLA,ATLÁNTICO,"3,138,337",99,99
4,CARTAGENA,BOLÍVAR,"2,692,478",102,102
5,CÚCUTA,NORTE DE SANTANDER,"1,879,397",95,95
6,SOLEDAD,ATLÁNTICO,"1,756,091",78,80
7,SOACHA,CUNDINAMARCA,"1,631,561",89,88
8,SANTA MARTA,MAGDALENA,"1,487,691",95,95
9,VALLEDUPAR,CESAR,"1,463,156",88,88